### ISSUE TITLE
Fishing Rod

### ISSUE THREAD

**Issue by Healthy-Eating** [MinecraftFrontiers/MF-Bug-Reports#21]
Finally figured out how to make a fishing rod and some bait! It worked for a few casts but I didn't catch anything. Later, I went back with bait and tried to fish however the rod wouldn't cast. I tried to build a new rod but neither of the rods would cast. 

Ignore the username by the way, my name is ZammyDog.

**Comment by endercrest** [comment]
Thanks! I can confirm this. Hopefully will have a bug fix for it soon!
