### ISSUE TITLE
Harvest Time

### ISSUE THREAD

**Issue by Saphiria** [MinecraftFrontiers/MF-Bug-Reports#5]
I was harvesting on the server for a few hours and I realised that the amount of time it takes to get a viable amount of resources of each of these consumes a large portion of time since the locations for these are really small with a large amount of waiting for even more of the products to regrow. So I was wondering if it possible to increase the size of these locations to hold more possible resources and to increase the time It takes for them to spawn in. If you cant do both then the best solution would be to increase the size of the location to hold even more of each product.

Credit: Leviathan (Also, I second this... I spent three hours getting sugar cane, and I got very little).

**Comment by endercrest** [comment]
@Saphiria As for the Sugarcane, it seems that you guys have been collecting near the market. This was never the intended sugar cane location. There is another location with larger quantity of sugar cane.

**Comment by Saphiria** [comment]
@endercrest No, there is a location in the mountains, thats the one we are using. (At least I and Leviathan am using).

**Comment by endercrest** [comment]
@Saphiria In the mountains? There should be one on the coast.

**Comment by Saphiria** [comment]
@endercrest I will get cords later. But, an image is at this thread. https://github.com/MinecraftFrontiers/Minecraft-Frontiers/issues/6

**Comment by endercrest** [comment]
That is not the primary location.

**Comment by Saphiria** [comment]
@endercrest Oh, wow. I wasn't aware of this.

**Comment by endercrest** [comment]
Resources will be getting changed in phase 2 comment to get the issue reoppend if this is still an issue.
