### ISSUE TITLE
Sugarcane Issue(s)

### ISSUE THREAD

**Issue by Saphiria** [MinecraftFrontiers/MF-Bug-Reports#6]
So, there are two issues with sugarcane that I have found.
![2016-01-01_16 41 34](https://cloud.githubusercontent.com/assets/12604271/12072499/ae5e0e88-b0a6-11e5-8c54-3fece3fd8edf.png)

I also think it would be nice if you would make some sugarcane along the waters edge, and maybe remake that pond, it doesn't seem to meet the build quality that you normally find in the server.

**Comment by endercrest** [comment]
This has been fixed in prototype phase 2
